import type { Metadata } from "next";
import { CartProvider } from './context/CartContext';
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";
// import Link from 'next/link';

// export const Header = () => (
//   <header className="p-4 bg-gray-100 flex justify-between items-center">
//     <h1 className="text-xl font-bold">E-Commerce</h1>
//     <Link href="/cart" className="text-blue-500 hover:underline">
//       View Cart
//     </Link>
//   </header>
// );

export const metadata: Metadata = {
  title: "Rocket Furniture",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="#" /> {/* To add Favicon in the title bar of Website */}
      </head>
      <body
        className={`text-[poppins] antialiased`}
      >
        <Navbar />
        <CartProvider>{children}</CartProvider>
        <Footer />
      </body>
    </html>
  );
}
